export {};

const DMV={x:-545.54,y:-204.05,z:38.22};
let near=false;
let currentVehicleId=0;
function loaded(){const id=Number(mp.players.local.getVariable('veloria:characterId')??0);return Number.isSafeInteger(id)&&id>0;}
function dist(){const p=mp.players.local.position;const dx=p.x-DMV.x,dy=p.y-DMV.y,dz=p.z-DMV.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
function execAll(code:string){mp.browsers.forEach((browser:BrowserMp)=>browser.execute(code));}
function vehicleId(){const v=mp.players.local.vehicle;if(!v)return 0;return Math.trunc(Number(v.getVariable('veloria:vehicleId')??0));}
mp.markers.new(1,new mp.Vector3(DMV.x,DMV.y,DMV.z-1),1.4,{color:[90,160,255,160],visible:true,dimension:0});
mp.labels.new('~w~VELORIA DMV\n~b~E ~w~— техпаспорт и номера',new mp.Vector3(DMV.x,DMV.y,DMV.z+.6),{los:false,font:4,drawDistance:25,dimension:0});
mp.events.add('render',()=>{near=loaded()&&dist()<=3.2;});
mp.keys.bind(0x45,true,()=>{if(!near||mp.gui.cursor.visible)return;currentVehicleId=vehicleId();if(!currentVehicleId){mp.events.callRemote('veloria:dmv:history');return;}mp.events.callRemote('veloria:dmv:registration',currentVehicleId);});
mp.events.add('veloria:dmv:registration',(raw:string)=>{let data:any;try{data=JSON.parse(String(raw??'{}'));}catch{return;}currentVehicleId=Number(data?.id)||0;const payload=JSON.stringify(data).replace(/</g,'\\u003c');mp.gui.cursor.show(true,true);execAll(`(()=>{document.getElementById('veloria-dmv-world')?.remove();const d=${payload};const root=document.createElement('div');root.id='veloria-dmv-world';root.style.cssText='position:fixed;inset:0;z-index:100000;background:rgba(4,7,12,.84);display:flex;align-items:center;justify-content:center;font-family:Inter,Arial;color:#fff';const card=document.createElement('section');card.style.cssText='width:720px;max-width:92vw;padding:26px;border-radius:22px;background:#0e1420;border:1px solid rgba(255,255,255,.1)';const row=(a,b)=>'<div style="display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06)"><span style="opacity:.55">'+a+'</span><b>'+String(b??'—')+'</b></div>';card.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:11px;letter-spacing:.2em;opacity:.45">VELORIA DMV</div><h2 style="margin:6px 0 0">Техпаспорт</h2></div><button id="vdmv-close">Закрыть</button></div><div style="margin-top:18px">'+row('Модель',d.model)+row('Госномер',d.plate)+row('VIN',d.vin)+row('Пробег',Math.round(Number(d.mileage||0))+' км')+row('Масло',Math.round(Number(d.oil||0))+'%')+row('АКБ',Math.round(Number(d.battery||0))+'%')+row('Техосмотр',d.inspection_until||'нет')+row('Страховка',d.insurance_until||'нет')+'</div><div style="display:flex;gap:10px;margin-top:18px"><input id="vdmv-plate" maxlength="8" placeholder="Новый номер" style="flex:1;padding:12px;border-radius:10px;border:1px solid rgba(255,255,255,.12);background:#080d16;color:#fff;text-transform:uppercase"><button id="vdmv-save" style="padding:12px 16px;border:0;border-radius:10px;background:#5a8cff;color:#fff;font-weight:800">Сменить за $25,000</button></div>';root.appendChild(card);document.body.appendChild(root);root.addEventListener('click',e=>{const t=e.target;if(t?.id==='vdmv-close')window.mp?.trigger('veloria:dmvWorld:close');if(t?.id==='vdmv-save'){const p=document.getElementById('vdmv-plate')?.value||'';window.mp?.trigger('veloria:dmvWorld:plate',Number(d.id),p);}});})();`);});
mp.events.add('veloria:dmvWorld:close',()=>{execAll(`document.getElementById('veloria-dmv-world')?.remove()`);mp.gui.cursor.show(false,false);});
mp.events.add('veloria:dmvWorld:plate',(id:number,plate:string)=>mp.events.callRemote('veloria:dmv:plate',Math.trunc(Number(id)),String(plate??'')));
mp.events.add('veloria:dmv:plateChanged',(id:number)=>{if(Number(id)===currentVehicleId)mp.events.callRemote('veloria:dmv:registration',currentVehicleId);});
