export {};
const POINT={x:-337.4,y:-136.9,z:39.0};
let near=false,open=false;
const dist=(a:{x:number;y:number;z:number})=>Math.hypot(a.x-POINT.x,a.y-POINT.y,a.z-POINT.z);
function exec(code:string){mp.browsers.forEach((b:BrowserMp)=>b.execute(code));}
function apply(raw:any,vehicle:VehicleMp|null=mp.players.local.vehicle??null){if(!vehicle)return;let t:any={};try{t=typeof raw==='string'?JSON.parse(raw):raw??{};}catch{}const v:any=vehicle;try{v.setMod?.(11,Math.max(-1,Number(t.engine??0)-1));v.setMod?.(12,Math.max(-1,Number(t.brakes??0)-1));v.setMod?.(13,Math.max(-1,Number(t.transmission??0)-1));v.setMod?.(15,Math.max(-1,Number(t.suspension??0)-1));if(typeof v.toggleMod==='function')v.toggleMod(18,Number(t.turbo??0)>0);else v.setMod?.(18,Number(t.turbo??0)>0?0:-1);}catch{}}
function close(){if(!open)return;open=false;mp.gui.cursor.show(false,false);exec(`document.getElementById('veloria-tuning')?.remove()`);}
function render(raw:string){let data:any={};try{data=JSON.parse(raw);}catch{return;}const safe=JSON.stringify(data).replace(/</g,'\\u003c');open=true;mp.gui.cursor.show(true,true);exec(`(()=>{document.getElementById('veloria-tuning')?.remove();const d=${safe};const names={engine:'Двигатель',brakes:'Тормоза',transmission:'Коробка',suspension:'Подвеска',turbo:'Турбо'};const root=document.createElement('div');root.id='veloria-tuning';root.style.cssText='position:fixed;inset:0;z-index:100003;background:rgba(4,6,12,.83);display:flex;align-items:center;justify-content:center;color:#fff;font-family:Inter,Arial';const card=document.createElement('div');card.style.cssText='width:min(760px,90vw);padding:26px;border-radius:24px;background:#0d1220;border:1px solid rgba(255,255,255,.1)';card.innerHTML='<div style="display:flex;justify-content:space-between"><div><small style="opacity:.5">VELORIA CUSTOMS</small><h2 style="margin:5px 0">'+String(d.model)+' · '+String(d.plate)+'</h2></div><button id="vt-close">Закрыть</button></div><div id="vt-list" style="display:grid;gap:10px;margin-top:20px"></div>';const list=card.querySelector('#vt-list');Object.entries(d.options||{}).forEach(([key,o])=>{const cur=Number((d.tuning||{})[key]||0),max=Number(o.max||0),base=Number(o.base||0);const row=document.createElement('div');row.style.cssText='padding:14px;border-radius:14px;background:rgba(255,255,255,.045);display:flex;align-items:center;justify-content:space-between;gap:12px';row.innerHTML='<b>'+names[key]+'</b><div style="display:flex;gap:7px;flex-wrap:wrap">'+Array.from({length:max+1},(_,i)=>'<button data-key="'+key+'" data-level="'+i+'" style="padding:8px 10px;border:0;border-radius:9px;background:'+(i===cur?'#7668ff':'rgba(255,255,255,.09)')+';color:#fff;cursor:pointer">'+(i===0?'Сток':'L'+i+' · $'+(base*i).toLocaleString())+'</button>').join('')+'</div>';list.appendChild(row)});root.appendChild(card);document.body.appendChild(root);root.addEventListener('click',e=>{const t=e.target;if(t?.id==='vt-close'){window.mp?.trigger('veloria:cef:tuning:close');return;}const b=t?.closest?.('[data-key]');if(b)window.mp?.trigger('veloria:cef:tuning:buy',b.dataset.key,Number(b.dataset.level));});})()`);}
mp.markers.new(1,new mp.Vector3(POINT.x,POINT.y,POINT.z-1),1.25,{color:[118,104,255,170],visible:true,dimension:0});mp.labels.new('~w~VELORIA CUSTOMS\n~p~E ~w~— тюнинг',new mp.Vector3(POINT.x,POINT.y,POINT.z+.5),{los:false,font:4,drawDistance:25,dimension:0});
mp.events.add('render',()=>{near=dist(mp.players.local.position)<=2.5;});
mp.keys.bind(0x45,true,()=>{if(near&&!open&&!mp.gui.cursor.visible&&mp.players.local.vehicle)mp.events.callRemote('veloria:vehicleTuning:data');});
mp.events.add('veloria:vehicleTuning:data',render);mp.events.add('veloria:vehicleTuning:apply',(raw:string)=>apply(raw));mp.events.add('entityStreamIn',(entity:EntityMp)=>{if(entity.type!=='vehicle')return;const raw=(entity as VehicleMp).getVariable('veloria:tuning');if(raw)setTimeout(()=>apply(raw,entity as VehicleMp),250);});mp.events.add('veloria:cef:tuning:buy',(key:string,level:number)=>mp.events.callRemote('veloria:vehicleTuning:buy',key,level));mp.events.add('veloria:cef:tuning:close',close);
