export {};

const SERVICE={x:-211.55,y:-1324.55,z:30.89};
function loaded(){const id=Number(mp.players.local.getVariable('veloria:characterId')??0);return Number.isSafeInteger(id)&&id>0;}
function distance(){const p=mp.players.local.position,dx=p.x-SERVICE.x,dy=p.y-SERVICE.y,dz=p.z-SERVICE.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
function execAll(code:string){mp.browsers.forEach((browser:BrowserMp)=>browser.execute(code));}
function close(){execAll(`document.getElementById('veloria-service')?.remove()`);mp.gui.cursor.show(false,false);}
mp.markers.new(1,new mp.Vector3(SERVICE.x,SERVICE.y,SERVICE.z-1),1.4,{color:[255,170,70,160],visible:true,dimension:0});
mp.labels.new('~w~VELORIA SERVICE\n~o~E ~w~— обслуживание',new mp.Vector3(SERVICE.x,SERVICE.y,SERVICE.z+.5),{los:false,font:4,drawDistance:25,dimension:0});
mp.keys.bind(0x45,true,()=>{if(loaded()&&distance()<=3&&!mp.gui.cursor.visible)mp.events.callRemote('veloria:vehicleService:data');});
mp.events.add('veloria:vehicleService:data',(raw:string)=>{let data:any;try{data=JSON.parse(String(raw??'{}'));}catch{return;}const payload=JSON.stringify(data).replace(/</g,'\\u003c');mp.gui.cursor.show(true,true);execAll(`(()=>{document.getElementById('veloria-service')?.remove();const d=${payload};const root=document.createElement('div');root.id='veloria-service';root.style.cssText='position:fixed;inset:0;z-index:100000;background:rgba(4,6,12,.82);display:flex;align-items:center;justify-content:center;font-family:Inter,Arial;color:#fff';const card=document.createElement('section');card.style.cssText='width:min(760px,90vw);padding:26px;border-radius:24px;background:#0d1320;border:1px solid rgba(255,255,255,.1)';const rows=[['repair','Полный ремонт',d.prices.repair],['oil','Замена масла',d.prices.oil],['battery','Обслуживание АКБ',d.prices.battery],['inspection','Техосмотр на 30 дней',d.prices.inspection],['insurance','Страховка на 7 дней',d.prices.insurance]];card.innerHTML='<div style="display:flex;justify-content:space-between"><div><div style="opacity:.5;font-size:11px;letter-spacing:.18em">VELORIA SERVICE</div><h2 style="margin:6px 0">'+String(d.model)+' · '+String(d.plate)+'</h2><div style="opacity:.65">Двигатель '+Math.round(Number(d.engineHealth))+' · Кузов '+Math.round(Number(d.bodyHealth))+' · Масло '+Math.round(Number(d.oilLevel))+'% · АКБ '+Math.round(Number(d.batteryHealth))+'%</div></div><button id="vs-close" style="height:40px;border:0;border-radius:10px;padding:0 14px;background:#20283a;color:#fff">Закрыть</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:22px">'+rows.map(r=>'<button data-service="'+r[0]+'" style="text-align:left;border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:16px;background:rgba(255,255,255,.045);color:#fff;cursor:pointer"><b>'+r[1]+'</b><div style="margin-top:6px;opacity:.65">$'+Number(r[2]).toLocaleString('en-US')+'</div></button>').join('')+'</div>';root.appendChild(card);document.body.appendChild(root);root.addEventListener('click',e=>{const t=e.target;if(t?.id==='vs-close'){window.mp?.trigger('veloria:cef:vehicleService:close');return;}const b=t?.closest?.('[data-service]');if(b)window.mp?.trigger('veloria:cef:vehicleService:buy',b.dataset.service);});})();`);});
mp.events.add('veloria:cef:vehicleService:buy',(type:string)=>mp.events.callRemote('veloria:vehicleService:buy',String(type??'')));
mp.events.add('veloria:cef:vehicleService:close',close);
