import { mysql } from '../../core/mysql';
import { changeBalance } from '../banking';

type JobDef={name:string;label:string;reward:number;points:{x:number;y:number;z:number}[]};
const JOBS:Record<string,JobDef>={
  courier:{name:'courier',label:'Курьер',reward:650,points:[{x:-425.1,y:-2789.4,z:6.0},{x:-711.4,y:-916.8,z:19.2},{x:1163.8,y:-323.9,z:69.2},{x:255.4,y:-1013.7,z:29.3}]},
  dockworker:{name:'dockworker',label:'Портовый рабочий',reward:800,points:[{x:1204.8,y:-3115.4,z:5.5},{x:1027.2,y:-3101.7,z:5.9},{x:914.6,y:-3087.4,z:5.9},{x:800.2,y:-2982.8,z:6.0}]}
};
const normalizeJobName=(value:string)=>String(value??'').trim().toLowerCase().slice(0,64);
function characterId(player:PlayerMp):number|null{const value=player.getVariable('veloria:characterId')??player.getVariable('characterId');return typeof value==='number'?value:null;}
function distance(player:PlayerMp,p:{x:number;y:number;z:number}){const dx=player.position.x-p.x,dy=player.position.y-p.y,dz=player.position.z-p.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
export async function startJob(characterId:number,job:string){
  const jobName=normalizeJobName(job);const def=JOBS[jobName];if(!def)throw new Error('INVALID_JOB');
  await mysql.query('INSERT INTO character_jobs(character_id,job_name,started_at,progress_json) VALUES(?,?,NOW(),?) ON DUPLICATE KEY UPDATE job_name=VALUES(job_name),started_at=NOW(),progress_json=VALUES(progress_json)',[characterId,jobName,JSON.stringify({completed:0,earned:0,step:0})]);
}
export async function stopJob(characterId:number){await mysql.query('DELETE FROM character_jobs WHERE character_id=?',[characterId]);}
export async function getJob(characterId:number){const[rows]=await mysql.query('SELECT * FROM character_jobs WHERE character_id=? LIMIT 1',[characterId]);return(rows as any[])[0]??null;}
export async function completeJobStep(characterId:number,reward:number,details:Record<string,unknown>={}){
  const normalizedReward=Math.trunc(Number(reward));if(!Number.isFinite(normalizedReward)||normalizedReward<0)throw new Error('INVALID_REWARD');
  const conn=await mysql.getConnection();try{await conn.beginTransaction();const[rows]:any=await conn.query('SELECT * FROM character_jobs WHERE character_id=? FOR UPDATE',[characterId]);const job=rows[0];if(!job)throw new Error('JOB_NOT_ACTIVE');let progress:Record<string,any>={};try{progress=job.progress_json?(typeof job.progress_json==='string'?JSON.parse(job.progress_json):job.progress_json):{};}catch{progress={};}progress.completed=Math.max(0,Number(progress.completed??0))+1;progress.earned=Math.max(0,Number(progress.earned??0))+normalizedReward;progress.last=details??{};await conn.query('UPDATE character_jobs SET progress_json=? WHERE character_id=?',[JSON.stringify(progress),characterId]);if(normalizedReward>0)await changeBalance(characterId,'cash',normalizedReward,'job_reward',String(job.job_name),conn);await conn.query('INSERT INTO job_history(character_id,job_name,reward,details_json) VALUES(?,?,?,?)',[characterId,String(job.job_name).slice(0,64),normalizedReward,JSON.stringify(details??{})]);await conn.commit();return progress;}catch(error){await conn.rollback();throw error;}finally{conn.release();}
}
function clientPayload(row:any){if(!row)return null;let progress:any={};try{progress=typeof row.progress_json==='string'?JSON.parse(row.progress_json):row.progress_json??{};}catch{}const def=JOBS[String(row.job_name)];const step=Math.max(0,Math.trunc(Number(progress.step)||0))%(def?.points.length||1);return{...row,progress,definition:def?{name:def.name,label:def.label,reward:def.reward,point:def.points[step]}:null};}
export function registerJobsModule():void{
  mp.events.add('veloria:job:get',async(player:PlayerMp)=>{const id=characterId(player);if(!id)return;try{player.call('veloria:job:data',[JSON.stringify(clientPayload(await getJob(id)))]);}catch{player.call('veloria:notify',['error','Не удалось загрузить работу']);}});
  mp.events.add('veloria:job:start',async(player:PlayerMp,job:string)=>{const id=characterId(player);if(!id)return;try{await startJob(id,String(job));player.call('veloria:job:data',[JSON.stringify(clientPayload(await getJob(id)))]);player.call('veloria:notify',['success','Работа начата']);}catch{player.call('veloria:notify',['error','Эта работа недоступна']);}});
  mp.events.add('veloria:job:stop',async(player:PlayerMp)=>{const id=characterId(player);if(!id)return;try{await stopJob(id);player.call('veloria:job:data',['null']);player.call('veloria:notify',['success','Работа завершена']);}catch{player.call('veloria:notify',['error','Не удалось завершить работу']);}});
  mp.events.add('veloria:job:complete',async(player:PlayerMp)=>{const id=characterId(player);if(!id)return;try{const row:any=await getJob(id);if(!row)throw new Error('JOB_NOT_ACTIVE');const def=JOBS[String(row.job_name)];if(!def)throw new Error('INVALID_JOB');let progress:any={};try{progress=typeof row.progress_json==='string'?JSON.parse(row.progress_json):row.progress_json??{};}catch{}const step=Math.max(0,Math.trunc(Number(progress.step)||0)%def.points.length);if(distance(player,def.points[step])>7)throw new Error('TOO_FAR');const updated=await completeJobStep(id,def.reward,{step,position:def.points[step]});updated.step=(step+1)%def.points.length;await mysql.query('UPDATE character_jobs SET progress_json=? WHERE character_id=?',[JSON.stringify(updated),id]);player.call('veloria:notify',['success',`Задание выполнено: +$${def.reward}`]);player.call('veloria:job:data',[JSON.stringify(clientPayload(await getJob(id)))]);}catch(error){const code=error instanceof Error?error.message:'';player.call('veloria:notify',['error',code==='TOO_FAR'?'Вы не находитесь в рабочей точке':'Не удалось выполнить задание']);}});
}
