import { mysql } from '../../core/mysql';
import { changeBalance } from '../banking';

const SERVICE_POINT={x:-211.55,y:-1324.55,z:30.89};
const PRICES={repair:2500,oil:800,battery:1200,inspection:1500,insurance:5000} as const;
type ServiceType=keyof typeof PRICES;
function characterId(player:PlayerMp):number|null{const value=player.getVariable('veloria:characterId')??player.getVariable('characterId');return typeof value==='number'?value:null;}
function distance(player:PlayerMp){const dx=player.position.x-SERVICE_POINT.x,dy=player.position.y-SERVICE_POINT.y,dz=player.position.z-SERVICE_POINT.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
function vehicleId(player:PlayerMp):number{const vehicle=player.vehicle;if(!vehicle)return 0;return Math.trunc(Number((vehicle as any).veloriaVehicleId??vehicle.getVariable('veloria:vehicleId')??0));}
async function ownedVehicle(player:PlayerMp,characterId:number){const id=vehicleId(player);if(!id)throw new Error('NO_VEHICLE');const[rows]:any=await mysql.query('SELECT * FROM character_vehicles WHERE id=? AND character_id=? LIMIT 1',[id,characterId]);if(!rows[0])throw new Error('VEHICLE_NOT_OWNED');return rows[0];}
function payload(row:any){return{id:Number(row.id),model:String(row.model),plate:String(row.plate),fuel:Number(row.fuel),engineHealth:Number(row.engine_health),bodyHealth:Number(row.body_health),mileage:Number(row.mileage??0),oilLevel:Number(row.oil??100),batteryHealth:Number(row.battery??100),inspectionUntil:row.inspection_until??null,insuranceUntil:row.insurance_until??null,prices:PRICES};}
export function registerVehicleServiceModule():void{
  mp.events.add('veloria:vehicleService:data',async(player:PlayerMp)=>{const cid=characterId(player);if(!cid)return;try{if(distance(player)>8)throw new Error('TOO_FAR');const row=await ownedVehicle(player,cid);player.call('veloria:vehicleService:data',[JSON.stringify(payload(row))]);}catch(error){const code=error instanceof Error?error.message:'';player.call('veloria:notify',['error',code==='NO_VEHICLE'?'Заедьте в сервис на своей машине':code==='VEHICLE_NOT_OWNED'?'Автомобиль вам не принадлежит':'Подъедьте к сервисному центру']);}});
  mp.events.add('veloria:vehicleService:buy',async(player:PlayerMp,rawType:string)=>{const cid=characterId(player);if(!cid)return;const type=String(rawType??'') as ServiceType;if(!(type in PRICES)){player.call('veloria:notify',['error','Неизвестная услуга']);return;}try{if(distance(player)>8)throw new Error('TOO_FAR');const row=await ownedVehicle(player,cid);const conn=await mysql.getConnection();try{await conn.beginTransaction();await changeBalance(cid,'bank',-PRICES[type],`vehicle_service_${type}`,`vehicle:${row.id}`,conn);if(type==='repair')await conn.query('UPDATE character_vehicles SET engine_health=1000,body_health=1000 WHERE id=?',[row.id]);else if(type==='oil')await conn.query('UPDATE character_vehicles SET oil=100 WHERE id=?',[row.id]);else if(type==='battery')await conn.query('UPDATE character_vehicles SET battery=100 WHERE id=?',[row.id]);else if(type==='inspection')await conn.query('UPDATE character_vehicles SET inspection_until=DATE_ADD(NOW(),INTERVAL 30 DAY) WHERE id=?',[row.id]);else if(type==='insurance')await conn.query('UPDATE character_vehicles SET insurance_until=DATE_ADD(GREATEST(COALESCE(insurance_until,NOW()),NOW()),INTERVAL 7 DAY) WHERE id=?',[row.id]);await conn.query('INSERT INTO vehicle_service_history(vehicle_id,character_id,service_type,cost,details_json) VALUES(?,?,?,?,?)',[row.id,cid,type,PRICES[type],JSON.stringify({plate:row.plate})]);await conn.commit();}catch(error){await conn.rollback();throw error;}finally{conn.release();}if(type==='repair'&&player.vehicle){(player.vehicle as any).engineHealth=1000;(player.vehicle as any).bodyHealth=1000;}const refreshed=await ownedVehicle(player,cid);player.call('veloria:vehicleService:data',[JSON.stringify(payload(refreshed))]);player.call('veloria:notify',['success',`Услуга оплачена: $${PRICES[type]}`]);}catch(error){const code=error instanceof Error?error.message:'';const message=code==='INSUFFICIENT_FUNDS'?'Недостаточно денег на банковском счёте':code==='VEHICLE_NOT_OWNED'?'Автомобиль вам не принадлежит':code==='NO_VEHICLE'?'Заедьте в сервис на машине':'Не удалось выполнить обслуживание';player.call('veloria:notify',['error',message]);}});
}
