export const LEVEL_FOR_PLAY_REWARD_MAX = 100;
export const MINUTES_FOR_PLAY_REWARD_MAX = 60 * 20;
export const CAR_FOR_PLAY_REWARD_MAX = "e63s";
export const CAR_NAME_FOR_CEF_FOR_PLAY_REWARD_MAX = "E-Series M213";