import { mysql } from '../../core/mysql';
import { changeBalance } from '../banking';

const TUNING_POINT={x:-337.4,y:-136.9,z:39.0};
const OPTIONS={engine:{max:4,base:5000},brakes:{max:3,base:3500},transmission:{max:3,base:4200},suspension:{max:4,base:2500},turbo:{max:1,base:7000}} as const;
type TuneKey=keyof typeof OPTIONS;
function characterId(player:PlayerMp):number|null{const value=player.getVariable('veloria:characterId')??player.getVariable('characterId');return typeof value==='number'?value:null;}
function distance(player:PlayerMp){const dx=player.position.x-TUNING_POINT.x,dy=player.position.y-TUNING_POINT.y,dz=player.position.z-TUNING_POINT.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
function vehicleId(player:PlayerMp):number{const vehicle=player.vehicle;if(!vehicle)return 0;return Math.trunc(Number((vehicle as any).veloriaVehicleId??vehicle.getVariable('veloria:vehicleId')??0));}
function parse(raw:any):Record<string,number>{if(!raw)return{};try{const value=typeof raw==='string'?JSON.parse(raw):raw;return value&&typeof value==='object'?value:{};}catch{return{};}}
function price(key:TuneKey,level:number){return OPTIONS[key].base*Math.max(1,level);}
async function owned(player:PlayerMp,cid:number){const id=vehicleId(player);if(!id)throw new Error('NO_VEHICLE');const[rows]:any=await mysql.query('SELECT id,character_id,model,plate,tuning_json FROM character_vehicles WHERE id=? AND character_id=? LIMIT 1',[id,cid]);if(!rows[0])throw new Error('VEHICLE_NOT_OWNED');return rows[0];}
function payload(row:any){const tuning=parse(row.tuning_json);return{vehicleId:Number(row.id),model:String(row.model),plate:String(row.plate),tuning,options:Object.fromEntries(Object.entries(OPTIONS).map(([key,value])=>[key,{max:value.max,base:value.base}]))};}
function applyToEntity(player:PlayerMp,tuning:Record<string,number>){if(!player.vehicle)return;player.vehicle.setVariable('veloria:tuning',JSON.stringify(tuning));player.call('veloria:vehicleTuning:apply',[JSON.stringify(tuning)]);}
export function registerVehicleTuningModule():void{
  mp.events.add('veloria:vehicleTuning:data',async(player:PlayerMp)=>{const cid=characterId(player);if(!cid)return;try{if(distance(player)>8)throw new Error('TOO_FAR');const row=await owned(player,cid);player.call('veloria:vehicleTuning:data',[JSON.stringify(payload(row))]);}catch(error){const code=error instanceof Error?error.message:'';player.call('veloria:notify',['error',code==='NO_VEHICLE'?'Заедьте в тюнинг на своей машине':code==='VEHICLE_NOT_OWNED'?'Автомобиль вам не принадлежит':'Подъедьте к тюнинг-центру']);}});
  mp.events.add('veloria:vehicleTuning:buy',async(player:PlayerMp,rawKey:string,rawLevel:number)=>{const cid=characterId(player);if(!cid)return;const key=String(rawKey??'') as TuneKey;if(!(key in OPTIONS)){player.call('veloria:notify',['error','Неизвестная модификация']);return;}const level=Math.trunc(Number(rawLevel));const config=OPTIONS[key];if(!Number.isFinite(level)||level<0||level>config.max){player.call('veloria:notify',['error','Недоступный уровень тюнинга']);return;}try{if(distance(player)>8)throw new Error('TOO_FAR');const row=await owned(player,cid);const current=parse(row.tuning_json);if(Number(current[key]??0)===level){player.call('veloria:notify',['info','Эта модификация уже установлена']);return;}const cost=level===0?500:price(key,level);const next={...current,[key]:level};const conn=await mysql.getConnection();try{await conn.beginTransaction();await changeBalance(cid,'bank',-cost,'vehicle_tuning',`${row.id}:${key}:${level}`,conn);await conn.query('UPDATE character_vehicles SET tuning_json=? WHERE id=? AND character_id=?',[JSON.stringify(next),row.id,cid]);await conn.query('INSERT INTO vehicle_service_history(vehicle_id,type,cost,mileage) VALUES(?,?,?,NULL)',[row.id,`tuning_${key}_${level}`,cost]);await conn.commit();}catch(error){await conn.rollback();throw error;}finally{conn.release();}applyToEntity(player,next);player.call('veloria:vehicleTuning:data',[JSON.stringify({...payload(row),tuning:next})]);player.call('veloria:notify',['success',`Тюнинг установлен: $${cost}`]);}catch(error){const code=error instanceof Error?error.message:'';player.call('veloria:notify',['error',code==='INSUFFICIENT_FUNDS'?'Недостаточно средств на банковском счёте':code==='VEHICLE_NOT_OWNED'?'Автомобиль вам не принадлежит':code==='TOO_FAR'?'Подъедьте к тюнинг-центру':'Не удалось установить тюнинг']);}});
}
