import { mysql } from '../../core/mysql';
import { randomBytes } from 'crypto';
export interface OwnedVehicle{id:number;characterId:number;model:string;plate:string;vin?:string;fuel:number;engineHealth:number;bodyHealth:number;mileage?:number;oil?:number;battery?:number;locked:boolean;engineOn:boolean;position?:unknown;}
const vin=()=>`VL${randomBytes(8).toString('hex').toUpperCase()}`;
export async function getCharacterVehicles(characterId:number):Promise<OwnedVehicle[]>{const[rows]=await mysql.query('SELECT * FROM character_vehicles WHERE character_id=?',[characterId]);return(rows as any[]).map(v=>({id:v.id,characterId:v.character_id,model:v.model,plate:v.plate,vin:v.vin,fuel:v.fuel,engineHealth:v.engine_health,bodyHealth:v.body_health,mileage:v.mileage,oil:v.oil,battery:v.battery,locked:!!v.locked,engineOn:!!v.engine_on,position:v.position_json?(typeof v.position_json==='string'?JSON.parse(v.position_json):v.position_json):undefined}));}
export async function createOwnedVehicle(characterId:number,model:string,plate:string,position?:unknown){const vehicleVin=vin();const[r]:any=await mysql.query('INSERT INTO character_vehicles(character_id,model,plate,vin,position_json) VALUES(?,?,?,?,?)',[characterId,model,plate,vehicleVin,position?JSON.stringify(position):null]);await giveVehicleKey(r.insertId,characterId);return{id:r.insertId,vin:vehicleVin};}
export async function hasVehicleKey(vehicleId:number,characterId:number){const[rows]=await mysql.query('SELECT 1 FROM vehicle_keys WHERE vehicle_id=? AND character_id=? LIMIT 1',[vehicleId,characterId]);return(rows as any[]).length>0;}
export async function giveVehicleKey(vehicleId:number,characterId:number){await mysql.query('INSERT IGNORE INTO vehicle_keys(vehicle_id,character_id) VALUES(?,?)',[vehicleId,characterId]);}
export async function revokeVehicleKey(vehicleId:number,characterId:number){await mysql.query('DELETE FROM vehicle_keys WHERE vehicle_id=? AND character_id=?',[vehicleId,characterId]);}
export async function transferVehicle(vehicleId:number,fromCharacterId:number,toCharacterId:number){const conn=await mysql.getConnection();try{await conn.beginTransaction();const[r]:any=await conn.query('UPDATE character_vehicles SET character_id=? WHERE id=? AND character_id=?',[toCharacterId,vehicleId,fromCharacterId]);if(!r.affectedRows)throw new Error('VEHICLE_NOT_OWNED');await conn.query('DELETE FROM vehicle_keys WHERE vehicle_id=?',[vehicleId]);await conn.query('INSERT INTO vehicle_keys(vehicle_id,character_id) VALUES(?,?)',[vehicleId,toCharacterId]);await conn.commit();return true;}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
export async function setVehicleState(id:number,patch:Partial<Pick<OwnedVehicle,'fuel'|'engineHealth'|'bodyHealth'|'locked'|'engineOn'|'position'>>):Promise<void>{const fields:string[]=[];const values:any[]=[];const map:any={fuel:'fuel',engineHealth:'engine_health',bodyHealth:'body_health',locked:'locked',engineOn:'engine_on',position:'position_json'};for(const[k,column]of Object.entries(map))if((patch as any)[k]!==undefined){fields.push(`${column}=?`);const value=(patch as any)[k];values.push(k==='position'?JSON.stringify(value):value);}if(!fields.length)return;values.push(id);await mysql.query(`UPDATE character_vehicles SET ${fields.join(',')} WHERE id=?`,values);}
export async function consumeFuel(id:number,amount:number){await mysql.query('UPDATE character_vehicles SET fuel=GREATEST(0,fuel-?) WHERE id=?',[Math.max(0,amount),id]);}
export async function addMileage(id:number,km:number){if(km<=0)return;await mysql.query('UPDATE character_vehicles SET mileage=mileage+?,oil=GREATEST(0,oil-?),battery=GREATEST(0,battery-?) WHERE id=?',[km,km*0.015,km*0.005,id]);}
export async function serviceVehicle(id:number){await mysql.query('UPDATE character_vehicles SET oil=100,battery=100,engine_health=1000,body_health=1000 WHERE id=?',[id]);}
export async function insureVehicle(id:number,days=30){await mysql.query('UPDATE character_vehicles SET insurance_until=DATE_ADD(NOW(),INTERVAL ? DAY) WHERE id=?',[Math.max(1,days),id]);}
