import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(process.cwd());
const out=resolve(root,'deploy');
await rm(out,{recursive:true,force:true});
await mkdir(resolve(out,'packages/veloria'),{recursive:true});
await mkdir(resolve(out,'client_packages/veloria/runtime'),{recursive:true});
await cp(resolve(root,'build/server'),resolve(out,'packages/veloria'),{recursive:true});
await cp(resolve(root,'build/client'),resolve(out,'client_packages/veloria/runtime'),{recursive:true});
await cp(resolve(root,'client_packages/veloria'),resolve(out,'client_packages/veloria'),{recursive:true,force:true});
await writeFile(resolve(out,'packages/veloria/index.js'),"require('./server/index.js');\n",'utf8');
await writeFile(resolve(out,'client_packages/index.js'),"require('./veloria/runtime/client/index.js');\n",'utf8');
await cp(resolve(root,'conf.json'),resolve(out,'conf.json'));
await cp(resolve(root,'.env.example'),resolve(out,'.env.example'));
await cp(resolve(root,'database'),resolve(out,'database'),{recursive:true});
console.log('VELORIA deploy bundle created:',out);
